"""empty message

Revision ID: 46d82b81aeac
Revises: 7eb2f300b5c6
Create Date: 2019-06-13 23:01:26.219936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d82b81aeac'
down_revision = '7eb2f300b5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('license')
    op.create_foreign_key(None, 'Building', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Building', type_='foreignkey')
    op.create_table('license',
    sa.Column('id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_premium', sa.BOOLEAN(), nullable=False),
    sa.CheckConstraint('is_active IN (0, 1)'),
    sa.CheckConstraint('is_premium IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
