"""empty message

Revision ID: 7eb2f300b5c6
Revises: 3ec0e6735e8f
Create Date: 2019-06-13 22:58:04.864656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb2f300b5c6'
down_revision = '3ec0e6735e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Building', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Building', type_='foreignkey')
    # ### end Alembic commands ###
