"""Building

Revision ID: 81e7e1d537e2
Revises: 9fb9c6617dc3
Create Date: 2019-05-22 18:11:44.174112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e7e1d537e2'
down_revision = '9fb9c6617dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Building', sa.Column('concrete_Value', sa.Integer(), nullable=True))
    op.add_column('Building', sa.Column('concrete_quantity', sa.Integer(), nullable=True))
    op.add_column('Building', sa.Column('copper_Value', sa.Integer(), nullable=True))
    op.add_column('Building', sa.Column('copper_quantity', sa.Integer(), nullable=True))
    op.add_column('Building', sa.Column('glass_Value', sa.Integer(), nullable=True))
    op.add_column('Building', sa.Column('glass_quantity', sa.Integer(), nullable=True))
    op.add_column('Building', sa.Column('polystyrene_Value', sa.Integer(), nullable=True))
    op.add_column('Building', sa.Column('polystyrene_quantity', sa.Integer(), nullable=True))
    op.add_column('Building', sa.Column('steel_Value', sa.Integer(), nullable=True))
    op.add_column('Building', sa.Column('steel_quantity', sa.Integer(), nullable=True))
    op.add_column('Building', sa.Column('timber_Value', sa.Integer(), nullable=True))
    op.add_column('Building', sa.Column('timber_quantity', sa.Integer(), nullable=True))
    op.add_column('Building', sa.Column('total_value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Building', 'total_value')
    op.drop_column('Building', 'timber_quantity')
    op.drop_column('Building', 'timber_Value')
    op.drop_column('Building', 'steel_quantity')
    op.drop_column('Building', 'steel_Value')
    op.drop_column('Building', 'polystyrene_quantity')
    op.drop_column('Building', 'polystyrene_Value')
    op.drop_column('Building', 'glass_quantity')
    op.drop_column('Building', 'glass_Value')
    op.drop_column('Building', 'copper_quantity')
    op.drop_column('Building', 'copper_Value')
    op.drop_column('Building', 'concrete_quantity')
    op.drop_column('Building', 'concrete_Value')
    # ### end Alembic commands ###
