"""empty message

Revision ID: 96a2c84e219e
Revises: a83b98a6940b
Create Date: 2019-06-22 22:20:09.666433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a2c84e219e'
down_revision = 'a83b98a6940b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Building', sa.Column('roof_flat', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Building', 'roof_flat')
    # ### end Alembic commands ###
