"""posts table

Revision ID: 9fb9c6617dc3
Revises: 22ecdf933b5e
Create Date: 2019-05-21 16:14:14.512592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb9c6617dc3'
down_revision = '22ecdf933b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_year', sa.Integer(), nullable=True),
    sa.Column('building_functionality', sa.String(length=120), nullable=True),
    sa.Column('square_meters', sa.Integer(), nullable=True),
    sa.Column('number_floors', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.drop_table('Building')
    # ### end Alembic commands ###
