"""empty message

Revision ID: a83b98a6940b
Revises: e3bae472c2c5
Create Date: 2019-06-22 22:11:43.009602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a83b98a6940b'
down_revision = 'e3bae472c2c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Building', sa.Column('windows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Building', 'windows')
    # ### end Alembic commands ###
