"""empty message

Revision ID: bdc8b55aaafb
Revises: fe4b2e33ab21
Create Date: 2019-06-13 22:44:47.298685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc8b55aaafb'
down_revision = 'fe4b2e33ab21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Building', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Building', type_='foreignkey')
    # ### end Alembic commands ###
