"""empty message

Revision ID: e3bae472c2c5
Revises: 1f2de3485b73
Create Date: 2019-06-22 21:52:49.988088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3bae472c2c5'
down_revision = '1f2de3485b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Building', sa.Column('house_number', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Building', 'house_number')
    # ### end Alembic commands ###
